name: CloneMe
main: com.liverookie.voidcore.Main
version: "0.1.0-SNAPSHOT"
api: ["1.0.13"]
load: POSTWORLD
author: Nukkit Projectes
description: Example plugin showing the API
commands:
  setbl:
    description: Example command
    usage: "/example"